name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.**
    paths-ignore:
      - "docs/**"
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    strategy:
      matrix:
        target:
          - arch: amd64
            os: linux
            runs-on: ubuntu-latest
            ext: so
          - arch: arm64
            os: linux
            runs-on: [self-hosted, Linux, ARM64]
            ext: so
          - arch: arm64
            os: macos
            runs-on: macos-latest
            ext: dylib
          - arch: amd64
            os: macos
            runs-on: macos-latest
            ext: dylib          
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Build
        run: |
          ./build.sh
      - name: Archive libgoast library (${{ matrix.target.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: libgoast-${{ matrix.target.arch }}.${{ matrix.target.ext }}
          path: libgoast-${{ matrix.target.arch }}.${{ matrix.target.ext }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')
    steps:
      - name: Determine Version
        run: |
          # determine version from tag
          export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          if [[ $VERSION != v* ]]
          then
            export VERSION=""
            echo "Building version-less (main or feature branch)"
          else
            # make version more Java-friendly by dropping the 'v'
            export VERSION=${VERSION:1:${#VERSION}}
            echo "Building as ${VERSION}"
          fi
          # store version in GitHub environment file
          echo "version=$VERSION" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: libgoast-arm64.dylib
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: libgoast-amd64.dylib
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: libgoast-amd64.so
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: libgoast-arm64.so
          path: .
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.version }}
          draft: false
          prerelease: false
          files: |
            libgoast-arm64.dylib
            libgoast-amd64.dylib
            libgoast-amd64.so
